name: Publish to hex.pm

on:
  push:
    tags:
      - '*'
      
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
          
    - name: Publish to Hex.pm
      uses: wesleimp/action-publish-hex@v1
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
